
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "Jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "d3a7bb0b-03c0-4b66-9f66-39388fd0ad67"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "190d35b2-64c5-41e8-b36a-3e89a5945754",
    "account_id_to": "ae3310e1-3036-4373-b902-b189f35415c0",
    "amount": 100
}

###

GET http://localhost:3003/balance/190d35b2-64c5-41e8-b36a-3e89a5945754 HTTP/1.1